export const UPSTREAM_COMMIT = '14f10a96a719a1d60aa02c582e674d5b197d5861';

const rootSource = (directory) =>
  `https://github.com/mcncarl/yichen-skills/blob/${UPSTREAM_COMMIT}/${directory}/SKILL.md`;

export const CATEGORY_META = {
  research: { label: '研究与获取', mark: '01' },
  content: { label: '内容与媒体', mark: '02' },
  platform: { label: '平台与私域', mark: '03' },
  memory: { label: '记忆与协作', mark: '04' },
};

export const LEVEL_META = {
  verified: { label: '已验证执行器', code: 'V', description: '含执行器，也有 schema、hash、回读、fixture 或测试契约。' },
  executor: { label: '执行器', code: 'E', description: '仓库内的确定性脚本承担主要工作。' },
  bridge: { label: '外部桥接', code: 'B', description: '编排浏览器、CLI、API、外部仓库或私有 Runtime。' },
  protocol: { label: '协议 / SOP', code: 'P', description: '主要将方法、模板和操作边界写成 Agent 可执行协议。' },
  deprecated: { label: '退役入口', code: 'D', description: '只保留旧名称兼容，不应作为新的执行入口。' },
};

export const ARCHITECTURE_LAYERS = [
  {
    id: 'host',
    index: '01',
    name: 'Agent 宿主',
    title: '理解意图，选择能力',
    body: 'Codex、Claude Code 或特定流程中的 ChatGPT / Grok 承担推理与决策。仓库自身没有中央 Planner、常驻循环或自主目标。',
    evidence: '模型负责理解与判断；Skill 负责约束选择空间。',
  },
  {
    id: 'protocol',
    index: '02',
    name: 'Skill 协议',
    title: '把个人经验写成可调用 SOP',
    body: 'SKILL.md 定义触发条件、前置检查、操作步骤、授权边界、失败策略和交付格式；references 继续承载更细的数据契约。',
    evidence: '这是仓库最核心的资产：可复用的方法，而非另一个模型。',
  },
  {
    id: 'execution',
    index: '03',
    name: '执行与适配',
    title: '把决定变成真实动作',
    body: 'Python、Node、Playwright、FFmpeg、SQLite、MCP、Computer Use 与外部 CLI/API 完成下载、转写、查询、渲染和平台操作。',
    evidence: '不同 Skill 的实现深度不同：有的只有 SOP，有的包含完整执行器。',
  },
  {
    id: 'evidence',
    index: '04',
    name: '证据与验收',
    title: '让“完成”可检查',
    body: 'manifest、handoff、hash、checkpoint、pending request、qa-report 与状态机将成功、失败、授权和来源变成结构化证据。',
    evidence: '证据化是它从“提示词收藏”走向“工作流协议库”的关键一步。',
  },
];

const skill = (entry) => ({ kind: 'skill', status: 'active', ...entry });

export const SKILLS = [
  skill({
    name: 'yichen-web-research', title: '互联网研究总入口', category: 'research', level: 'verified',
    summary: '把多阶段研究拆成搜索、归档、收藏与 ASR，并汇总为纵向历史、横向现状和证据报告。',
    input: '研究目标、范围、时间、地区、受众、语言、来源约束。',
    output: '研究计划、证据 bundle、时间线、横向矩阵、矛盾与保留缺口。',
    mechanism: '离线规划器 + 子 Skill 路由 + 证据组装器；它是研究编排器，不是搜索引擎。',
    deps: ['统一搜索', '内容归档', '收藏导出', 'ASR（按需）'],
    boundary: '搜索不等于归档授权；候选或已打开原文不自动等于事实已验证。',
    value: '展示了如何用总入口稳定模糊意图，再把执行交给更窄的能力。',
    source: rootSource('yichen-web-research'),
  }),
  skill({
    name: 'yichen-unified-search', title: '跨平台统一搜索', category: 'research', level: 'verified',
    summary: '统一路由网页、GitHub、微信、微博、小红书、抖音、知乎、X、B站、YouTube 等候选发现。',
    input: '查询词、平台、模式、时间范围、数量与筛选条件。',
    output: 'schema 1.0 envelope：request、routes、candidates、coverage、errors。',
    mechanism: '10 个 Python 路由/适配脚本将异构后端归一化，并记录 canonical URL、稳定 ID 与 provenance。',
    deps: ['AnySearch / Firecrawl', 'Grok / FxTwitter', 'OpenCLI / gh / yt-dlp（按路线）'],
    boundary: '不处理已知 URL，不下载、不归档、不读私人收藏；搜索摘要不能替代正文证据。',
    value: '统一的候选数据契约比“接更多搜索 API”更值得复用。',
    source: rootSource('yichen-unified-search'),
  }),
  skill({
    name: 'yichen-content-archive', title: '已知内容归档', category: 'research', level: 'verified',
    summary: '读取、下载或归档明确 URL、URL 文件、已确认候选与有限容器。',
    input: '明确 URL、确认后的候选或 known_collection，以及 read / download / archive 操作。',
    output: '平台目录、archive-manifest.jsonl、run-summary.json、failures.json 与标准 handoff。',
    mechanism: '平台执行器 + 排他创建 + 只读 checkpoint + SHA-256 续跑校验。',
    deps: ['平台解析器', 'Playwright / yt-dlp 等按平台工具'],
    boundary: '不做关键词发现或推荐补量；下载必须由用户明确要求。',
    value: '把“发现候选”和“读取/保存内容”拆成两个授权阶段。',
    source: rootSource('yichen-content-archive'),
  }),
  skill({
    name: 'yichen-bookmarks-export', title: '私人收藏链接导出', category: 'research', level: 'verified',
    summary: '只读导出小红书、抖音收藏和 X/Twitter 书签的链接清单。',
    input: '当前任务明确授权的平台、范围和输出位置。',
    output: '平台 URL 文件、export-summary.json 与 handoff.json。',
    mechanism: '浏览器页面滚动提取；X 使用独立 Field Theory GraphQL-only 本地索引。',
    deps: ['用户 Chrome 登录态', 'Field Theory（X 路线）'],
    boundary: '只导链接，不读正文、不分析、不下载；授权不跨平台、不跨任务、不转移给归档。',
    value: '适合作为私人数据访问的最小授权范例。',
    source: rootSource('yichen-bookmarks-export'),
  }),
  skill({
    name: 'yichen-chatgpt-web-research', title: 'ChatGPT 网页研究', category: 'research', level: 'bridge',
    summary: '通过用户已登录的 ChatGPT 官方网页完成产品、市场、竞品研究或第二意见。',
    input: '研究问题、浏览器 profile、目标模型和报告结构。',
    output: '原始 Markdown、可读报告、对话 URL、提取方式与完成标记。',
    mechanism: '优先浏览器扩展控制真实页面，失败后使用可见 Computer Use，以唯一 marker 判断完整性。',
    deps: ['ChatGPT 登录态', 'Chrome / Computer Use 宿主能力'],
    boundary: '不以 API、普通网页搜索或另一个免费账号替代用户指定路线。',
    value: '说明 Skill 可以封装“使用某个产品”的稳定操作协议，而不一定自带执行代码。',
    source: rootSource('yichen-chatgpt-web-research'),
  }),
  skill({
    name: 'yichen-grok-consult', title: 'Grok 顾问插件', category: 'research', level: 'bridge', kind: 'plugin',
    summary: '在 GPT 主导的 Codex 会话里，将 Grok 用作只读顾问、审查者和 X 原生搜索器。',
    input: '咨询、审查、挑战问题或 X 搜索条件。',
    output: 'Grok 意见、审查结果，或带原生调用证明和确定性时间的 X 候选。',
    mechanism: 'Node MCP server 启动隔离 Grok CLI 会话，并为搜索设置受限回退链。',
    deps: ['Grok CLI / xAI', 'FxTwitter 回退', '可选 OpenCLI / xreach'],
    boundary: '普通顾问禁用本地文件、shell、记忆和子 Agent；查询与回复可能发送给 xAI。',
    value: '这是唯一插件型条目，展示 Skill 与 MCP 工具如何组合，但仍不是 Agent 本体。',
    source: `https://github.com/mcncarl/yichen-skills/blob/${UPSTREAM_COMMIT}/plugins/yichen-grok-consult/skills/yichen-grok-consult/SKILL.md`,
  }),
  skill({
    name: 'yichen-asr', title: 'ASR 统一选择器', category: 'content', level: 'verified',
    summary: '在 Step ASR 与豆包 ASR 之间按全文、时间戳、字幕和粗剪需求选择最小路线。',
    input: '本地媒体、时间戳/SRT/停顿分析需求、指定 provider。',
    output: 'provider、mode、文件、request ID、计费状态与错误。',
    mechanism: '离线路由器 + 不读取密钥内容的 doctor；自身不是第三种识别模型。',
    deps: ['外部 Step 执行器', 'yichen-volc-asr'],
    boundary: '任务提交后必须恢复原 provider，不能跨服务商重复提交和重复计费。',
    value: '把供应商选择逻辑与执行器解耦，便于未来替换后端。',
    source: rootSource('yichen-asr'),
  }),
  skill({
    name: 'yichen-volc-asr', title: '豆包转写与口播粗剪', category: 'content', level: 'executor',
    summary: '完成长音频转写、SRT 生成，并按时间戳制作口播视频自动粗剪。',
    input: '本地媒体工作副本、缓存/request ID、转写或剪辑模式。',
    output: '文本、SRT、ASR cache、pending 记录、粗剪 MP4 与删留方案。',
    mechanism: 'FFmpeg 音轨处理 + 火山长音频 ASR + 时间区间拼接 + 粗剪复转写审核。',
    deps: ['Volcengine ASR', 'FFmpeg / ffprobe'],
    boundary: '原片不动；媒体会上传第三方；费用、额度和主观删留仍需外部确认。',
    value: '展示 pending request 如何避免付费 API 的重复提交。',
    source: rootSource('yichen-volc-asr'),
  }),
  skill({
    name: 'yichen-video-content', title: '视频内容拆解框架', category: 'content', level: 'protocol',
    summary: '按 13 个模块拆解口播稿的结构、逐句作用、表达效率、认知落差和可模仿模板。',
    input: '视频元数据与完整口播稿。',
    output: '结构化拆解报告、问题诊断与具体优化建议。',
    mechanism: '宿主模型依照固定分析框架生成，不含独立内容分析程序。',
    deps: ['宿主模型'],
    boundary: '“爆款”“AI 味”等结论缺少量化基线，质量高度依赖模型判断。',
    value: '最接近“把个人日常方法整理成技能”的纯协议案例。',
    source: rootSource('yichen-video-content'),
  }),
  skill({
    name: 'yichen-jianying-editor', title: '剪映桌面编辑 SOP', category: 'content', level: 'bridge',
    summary: '封装剪映/CapCut 的导入、时间线、视觉精修、字幕与导出操作流程。',
    input: '媒体文件、用户要求和当前剪映项目状态。',
    output: '剪映项目修改、导出视频与可选操作日志。',
    mechanism: '依赖 Computer Use 控制桌面端；仓库没有剪映自动化执行器。',
    deps: ['剪映 / CapCut', 'Computer Use'],
    boundary: 'ASR 删停顿和自动粗剪应先交给 yichen-volc-asr；UI 变化会破坏流程。',
    value: '适合把重复桌面操作沉淀为 SOP，但企业化需更可靠的自动化层。',
    source: rootSource('yichen-jianying-editor'),
  }),
  skill({
    name: 'x-article-draft-uploader', title: 'X Article 草稿上传', category: 'content', level: 'verified',
    summary: '将 Markdown/Obsidian 长文与媒体写入 X Article 草稿，并在重载后验证持久化；不发布。',
    input: 'Markdown、封面、正文图片与表格。',
    output: '已保存草稿、正文/媒体校验证据和 persistence_verified 状态。',
    mechanism: '独立 Playwright Chromium + Chrome cookies；用 code point、SHA-256、checkpoint 与 dHash 验证。',
    deps: ['Playwright', 'Chrome cookies', 'X 登录态'],
    boundary: '只保存草稿，不点击发布；cookie 敏感，X DOM 变化可能导致失效。',
    value: '代表仓库里“写入后回读验证”的最高成熟度做法之一。',
    source: rootSource('yichen-x-article-draft-uploader'),
  }),
  skill({
    name: 'yichen-x-slicer', title: 'X 内容切片成图/视频', category: 'content', level: 'verified',
    summary: '把公开 X Post、Quote 或同作者 Thread 生成 1080×1440 PNG、ZIP 与 H.264 MP4。',
    input: '一个公开 X URL、视觉模板与输出参数。',
    output: '卡片 PNG、ZIP、MP4 与文本/图像/视频/音频 QA 证据。',
    mechanism: 'FxTwitter 取公开数据，Playwright 渲染，FFmpeg 编码；含 11 套模板。',
    deps: ['FxTwitter', 'Playwright', 'FFmpeg'],
    boundary: '不做 TTS、配音、BGM、剪映或发布；只允许限定媒体主机与内容签名。',
    value: '说明多媒体产物也能用可机器检查的验收合同管理。',
    source: rootSource('yichen-x-slicer'),
  }),
  skill({
    name: 'yichen-wechat-local-vault', title: 'Mac 微信本地资产库', category: 'platform', level: 'executor',
    summary: '将 Mac 微信 4.x 本地数据库制成可查询的明文快照、会话导出和摘要素材包。',
    input: '本机微信数据库、已保存或经授权捕获的 key、明确会话/时间/内容范围。',
    output: '私密 vault、manifest、联系人/会话/消息查询与 Markdown 导出。',
    mechanism: 'key 匹配/Frida 捕获 + SQLCipher 4 页面解密 + 全量/增量只读快照。',
    deps: ['macOS 微信 4.x', 'Frida / SQLCipher 兼容实现'],
    boundary: '高敏感私人数据；默认不操作 UI，不把 key、明文库和身份信息放进项目或云盘。',
    value: '方法可借鉴，但数据合规与运行时隔离必须先于功能迁移。',
    source: rootSource('yichen-wechat-local-vault'),
  }),
  skill({
    name: 'yichen-wechat-windows-reader', title: 'Windows 微信快照读取', category: 'platform', level: 'verified', status: 'experimental',
    summary: '只读查询用户显式提供的微信明文 SQLite 静态快照，不负责发现、复制或解密。',
    input: '已 checkpoint、无 sidecar、带 UUIDv4 manifest 的明文 SQLite 快照。',
    output: '会话候选、历史、搜索结果和 Markdown 导出。',
    mechanism: '路径/reparse/UNC 检查、schema 白名单、完整性校验、immutable + query_only 连接。',
    deps: ['Windows', '受支持的合成 fixture schema'],
    boundary: '不访问 Weixin.exe、进程内存、密钥、加密库或网络；尚未证明广泛真实版本兼容。',
    value: '提供了“不可信本地输入 + 真正只读连接”的安全实现样板。',
    source: rootSource('yichen-wechat-windows-reader'),
  }),
  skill({
    name: 'yichen-wechat-mp-batch-exporter', title: '公众号批量导出', category: 'platform', level: 'bridge',
    summary: '导出公众号已知文章或历史内容，可附带原创清单、互动指标和评论。',
    input: '已知文章 URL、历史目标、自有登录/凭据及可选指标需求。',
    output: 'Markdown/HTML/JSON、图片、history summary、去重/原创清单和可选评论。',
    mechanism: '内置 URL 下载/分析/doctor；完整历史与指标调用外部工具。',
    deps: ['wechat-article-exporter', 'wxdown-service（指标/评论）'],
    boundary: '不控制微信 UI；QR 登录、证书、代理和凭据需人工确认。',
    value: '提醒我们必须区分仓库自带实现、适配器与外部产品能力。',
    source: rootSource('yichen-wechat-mp-batch-exporter'),
  }),
  skill({
    name: 'yichen-wecom-local-vault', title: 'Mac 企微本地资产库', category: 'platform', level: 'executor',
    summary: '对 Mac 企业微信 5.x 执行密钥捕获、解密快照与只读查询。',
    input: '获授权的本地数据集、可选 key、明确 attach/重签副本授权。',
    output: '时间戳明文快照、联系人/会话/消息查询和 Markdown/JSON 导出。',
    mechanism: 'Frida、ad-hoc 重签副本、Mach VM 扫描、AES key 验证与 WAL 合并。',
    deps: ['macOS 企业微信 5.x', 'Frida / codesign'],
    boundary: '不改源库、不发送消息、不自动关闭 SIP；企业数据敏感且版本耦合强。',
    value: '适合作为敏感数据边界审计的反例与研究样本，不宜直接照搬。',
    source: rootSource('yichen-wecom-local-vault'),
  }),
  skill({
    name: 'yichen-wecom-operations', title: '企微云端操作', category: 'platform', level: 'bridge',
    summary: '通过官方 CLI 创建或更新企微文档、待办、会议与日程，并保留本地回执。',
    input: '当前任务明确要求、目标资源、Markdown 文档与可选图片 helper。',
    output: '远程资源链接、本地 0600 回执和回读状态。',
    mechanism: 'doctor 校验 CLI、配置与权限，脚本完成智能文档预检和执行。',
    deps: ['官方 @wecom/cli', '私有图片 helper（可选）'],
    boundary: '永不发企微消息；删除、取消和覆盖需重确认；errcode=0 才是远程成功。',
    value: '把外部写操作做成 preflight—执行—回读的可审计流程。',
    source: rootSource('yichen-wecom-operations'),
  }),
  skill({
    name: 'yichen-mac-wechat-dual-open', title: 'Mac 微信双开', category: 'platform', level: 'executor',
    summary: '不注入原应用，通过复制、换 bundle id 和重签创建第二个微信实例。',
    input: '本机微信应用与创建/修复请求。',
    output: '~/Applications/WeChat-2.app、独立 bundle id、语言设置与可识别图标。',
    mechanism: '复制应用、修改 Info.plist、ad-hoc codesign、Launch Services 注册与图标处理。',
    deps: ['macOS', 'codesign', 'Pillow'],
    boundary: '不修改 /Applications/WeChat.app；删除旧副本前询问；更新后通常需 repair。',
    value: '一个小而完整的个人环境自动化案例，团队通用价值有限。',
    source: rootSource('yichen-mac-wechat-dual-open'),
  }),
  skill({
    name: 'yichen-summary', title: '对话总结入 Obsidian', category: 'memory', level: 'protocol',
    summary: '筛选当前对话的决策、方案、代码、经验和错误教训，写成 Obsidian Markdown。',
    input: '当前完整对话与目标 Obsidian 路径。',
    output: '背景、核心内容、解决方案、关键要点和相关信息组成的笔记。',
    mechanism: '宿主模型筛选与生成，再通过 shell 写文件；没有独立解析执行器。',
    deps: ['宿主模型', '本地 Obsidian vault'],
    boundary: '总结质量与隐私筛选依赖模型；示例缺少明确冲突保护。',
    value: '最直观体现“将个人日常收尾动作产品化为 Skill”。',
    source: rootSource('yichen-summary'),
  }),
  skill({
    name: 'yichen-agent-memory', title: '跨 Agent 记忆协议', category: 'memory', level: 'bridge',
    summary: '安装和维护共享 Memory Vault，使 Claude Code 与 Codex 使用同一 Markdown 事实源。',
    input: '记忆库、session claim、搜索/写前 reconcile/closeout/audit 操作。',
    output: 'Markdown 事实、SQLite/FTS 索引、可选语义索引与审计结果。',
    mechanism: 'Skill 只提供 Agent runbook；核心脚本位于独立 agent-memory-vault 仓库。',
    deps: ['mcncarl/agent-memory-vault', '可选 Zvec'],
    boundary: '自动记忆不是正式事实源；搜索命中必须回读 Markdown；修索引不能改事实。',
    value: '值得复用的是“事实源与派生索引分离”及多会话 claim ledger。',
    source: rootSource('yichen-agent-memory'),
  }),
  skill({
    name: 'yichen-codex-chatgpt', title: 'Codex × ChatGPT 双 Agent 协作', category: 'memory', level: 'bridge',
    summary: '让 ChatGPT 负责研究/架构/只读审查，Codex 独占本地写入与测试。',
    input: 'research、code、hybrid、review 或显式 local-only 任务。',
    output: '计划、执行证据、审查结论和 DONE / BLOCKED / ERROR 等状态。',
    mechanism: '有限状态机 + Secure Tunnel + 七个只读 remote-review MCP 工具 + 消息 marker。',
    deps: ['私有 Tunnel / Runtime Key / App / MCP runtime'],
    boundary: 'ChatGPT 建议不是授权，Codex 是唯一 writer；私有组件缺失时无法完整复现。',
    value: '应用层“单写者 + 可验证交接 + 防重复执行”协议非常值得借鉴。',
    source: rootSource('yichen-codex-chatgpt'),
  }),
  skill({
    name: 'yichen-social-bookmarks-exporter', title: '旧收藏导出兼容名', category: 'memory', level: 'deprecated', kind: 'alias', status: 'deprecated',
    summary: '只在用户明确点名旧名称时触发，然后迁移到 yichen-bookmarks-export。',
    input: '旧 Skill 名称调用。',
    output: '重路由到现行收藏导出 Skill。',
    mechanism: '兼容提示与迁移指引；目录虽有旧脚本，但协议明确禁止执行。',
    deps: ['yichen-bookmarks-export'],
    boundary: '不是第二套独立导出能力，也不应成为新项目入口。',
    value: '提醒我们为 Skill 重命名设计显式、可退役的兼容层。',
    source: rootSource('yichen-social-bookmarks-exporter'),
  }),
];

export const RESEARCH_STATS = {
  skillFiles: 22,
  rootSkills: 21,
  plugins: 1,
  codeFiles: 84,
  testFiles: 30,
  testsTotal: 367,
  testsPassed: 354,
  testsSkipped: 1,
  testsFailed: 12,
};

export const SKILL_SCENARIOS = {
  'yichen-web-research': '需要同时回答“过去怎么演变、现在谁在做、未来机会在哪”的行业或产品深度研究。',
  'yichen-unified-search': '围绕一个主题从网页、GitHub、X、微信、视频平台等渠道批量发现候选线索。',
  'yichen-content-archive': '已经有明确链接，希望把正文、媒体和来源信息稳定保存为本地研究资产。',
  'yichen-bookmarks-export': '把本人账号中的小红书、抖音或 X 收藏先导出为链接清单，再决定是否继续处理。',
  'yichen-chatgpt-web-research': '需要利用本人 ChatGPT Pro 网页账号完成竞品研究、市场分析或第二意见。',
  'yichen-grok-consult': '研究 X 上的实时讨论，或让另一个模型对方案做只读审查和反方挑战。',
  'yichen-asr': '手头已有音视频，需要根据全文、时间戳、字幕或粗剪目标自动选择 ASR 路线。',
  'yichen-volc-asr': '把访谈、课程或口播视频转成带时间戳文本、SRT，并生成去停顿粗剪。',
  'yichen-video-content': '拆解一个对标视频为何有效，定位开头、结构、逐句作用和可复用表达模板。',
  'yichen-jianying-editor': '已有粗剪，希望在剪映中完成字幕、节奏、视觉精修和成片导出。',
  'x-article-draft-uploader': '将本地 Markdown 长文、图片和表格可靠写入 X Article 草稿，交给人工发布。',
  'yichen-x-slicer': '把一个 X Post 或 Thread 改造成适合社交传播的竖版图片组、ZIP 和短视频。',
  'yichen-wechat-local-vault': '在本人 Mac 上对微信历史进行本地、只读、范围明确的检索、导出或群聊摘要。',
  'yichen-wechat-windows-reader': '安全读取用户已经准备好的 Windows 微信明文静态快照，不接触运行中客户端。',
  'yichen-wechat-mp-batch-exporter': '归档某个公众号的已知文章或历史内容，并区分发布批次、URL 条目和原创文章。',
  'yichen-wecom-local-vault': '在获授权的 Mac 企业微信数据集上制作只读快照，用于本地检索与导出。',
  'yichen-wecom-operations': '把已确认的研究结果写入企微文档、待办、会议或日程，并保留回执。',
  'yichen-mac-wechat-dual-open': '个人 Mac 需要同时登录两个微信实例，并希望不修改原始应用。',
  'yichen-summary': '一次复杂对话或项目阶段结束后，把决策、方案和教训沉淀成 Obsidian 笔记。',
  'yichen-agent-memory': 'Codex 与 Claude Code 等多个 Agent 需要共享事实，同时避免索引覆盖事实或会话互相提交。',
  'yichen-codex-chatgpt': '让 ChatGPT 负责研究和只读审查、Codex 负责唯一写入与测试的复杂代码协作。',
  'yichen-social-bookmarks-exporter': '旧自动化仍调用历史名称时提供迁移入口；所有新任务应改用 yichen-bookmarks-export。',
};

export const WORKFLOW_SCENARIOS = [
  {
    id: 'creator',
    label: '内容创作闭环',
    title: '从 90 天趋势研究，到长文草稿与视觉切片',
    summary: '一个 Agent 主导、10 个相关 Skill 按需接力。每一步都用产物交接，而不是靠上一段对话“记得差不多”。',
    brief: '示例目标：研究过去 90 天 AI 视频创作者的高频痛点，形成一篇 X 长文草稿、6 张传播切片，并沉淀到个人知识库。',
    note: '演示数据为说明性样例，不代表已调用平台或得到真实结果。',
    stages: [
      {
        title: '锁定研究问题', phase: 'PLAN', skills: ['yichen-web-research'],
        decision: '先固定时间、平台、受众和最终内容形态，再决定需要哪些下游能力。',
        input: '“过去 90 天，AI 视频创作者最常见的工作流痛点是什么？”',
        operation: '生成横向平台矩阵、证据要求和 7 段执行计划。',
        handoff: 'research-brief.json · scope locked',
        guard: '范围字段不完整时，不进入正式搜索。',
        effect: '把一个宽泛选题压缩成可验证、可交接的研究任务。',
        sample: '范围：90 天｜受众：个人创作者｜地区：中文互联网 + X｜交付：长文 + 6 张切片',
      },
      {
        title: '发现跨平台候选', phase: 'DISCOVER', skills: ['yichen-unified-search', 'yichen-grok-consult'],
        decision: '统一搜索负责广度；Grok 只补充 X 原生讨论与反方信号。',
        input: '研究 brief + 8 组查询词 + 平台与时间窗。',
        operation: '归一化网页、GitHub、X、B站、YouTube 与小红书候选，并保留真实后端。',
        handoff: 'candidate-envelope.json · 48 illustrative candidates',
        guard: '候选不是事实；搜索完成不自动取得下载权限。',
        effect: '得到可排序、可追溯、可人工确认的材料池。',
        sample: '示例：48 条候选｜6 个来源域｜7 条待核验冲突｜所有缺失指标保持 null',
      },
      {
        title: '确认并归档原文', phase: 'ARCHIVE', skills: ['yichen-content-archive'],
        decision: 'Agent 与用户确认 12 条高价值候选，只把明确范围交给归档器。',
        input: '12 个已确认 URL + archive 授权。',
        operation: '读取正文和元数据，生成逐 URL 状态、hash 与失败清单。',
        handoff: 'archive-manifest.jsonl · 12 scoped inputs',
        guard: '不为了“凑够数量”继续搜索；未授权媒体不下载。',
        effect: '在线线索变成稳定、可回读的本地证据包。',
        sample: '示例：10 条归档成功｜1 条仅元数据｜1 条失败保留原因｜0 次越界补量',
      },
      {
        title: '转写视频证据', phase: 'TRANSCRIBE', skills: ['yichen-asr', 'yichen-volc-asr'],
        decision: '因为需要时间戳与引用定位，路由到豆包 ASR，而不是纯全文路线。',
        input: '3 段已授权视频工作副本。',
        operation: '提取音轨、提交转写、生成 SRT，并保留 request ID 与 pending 状态。',
        handoff: 'transcripts/ + subtitles/ + asr-receipt.json',
        guard: '提交后锁定 provider，避免切换服务商造成重复计费。',
        effect: '不可检索的视频内容变成带定位信息的文本证据。',
        sample: '示例：3 份逐字稿｜3 份 SRT｜42 个可引用时间点｜费用状态可追踪',
      },
      {
        title: '提炼内容结构', phase: 'SYNTHESIZE', skills: ['yichen-video-content', 'yichen-chatgpt-web-research'],
        decision: '先用固定框架拆解表达，再让 ChatGPT 网页路线提供独立第二意见。',
        input: '12 份归档材料 + 3 份逐字稿 + 完成 marker。',
        operation: '标记开头、逐句作用、认知落差、素材与可模仿结构，比较不同来源。',
        handoff: 'content-patterns.md · claim-evidence matrix',
        guard: '模型意见仍是分析，不把“爆款判断”写成已证实事实。',
        effect: '原始材料被压缩为可直接支撑创作的结构与论点。',
        sample: '示例：5 个高频痛点｜8 种开头结构｜4 组矛盾观点｜每个 claim 带 locator',
      },
      {
        title: '生成草稿与传播资产', phase: 'PRODUCE', skills: ['x-article-draft-uploader', 'yichen-x-slicer'],
        decision: '长文进入 X 草稿；核心框架同时改造成 6 张卡片和 1 条短视频。',
        input: '经人工确认的 Markdown、封面和视觉模板。',
        operation: '写入草稿后重载验证；切片管线检查文本覆盖、图片尺寸、ZIP 与视频。',
        handoff: 'draft-receipt.json + 6 PNG + ZIP + MP4 + qa-report.json',
        guard: '只保存草稿，不发布；不自动生成配音、BGM 或平台互动。',
        effect: '同一份证据报告形成长文、图片组与视频三种可审核载体。',
        sample: '示例：正文 hash 一致｜6/6 卡片通过｜MP4 1080×1440 / H.264 / 30fps',
      },
      {
        title: '沉淀决策与记忆', phase: 'REMEMBER', skills: ['yichen-summary', 'yichen-agent-memory'],
        decision: '把研究结论、创作取舍和失败记录写回 Markdown 事实源，再更新派生索引。',
        input: '最终报告、交付物回执、QA 结果与本次对话决策。',
        operation: '生成 Obsidian 总结，执行 prewrite reconcile、claim、closeout 和索引。',
        handoff: 'AI-creator-trends.md + memory closeout receipt',
        guard: '自动记忆不是事实源；搜索命中仍需回读 Markdown。',
        effect: '本次工作不只产出内容，还成为下一次 Agent 可复用的组织知识。',
        sample: '示例：1 份事实笔记｜14 个来源引用｜7 条决策理由｜派生索引可重建',
      },
    ],
    outcomes: [
      { title: '研究证据包', detail: 'brief、48 条候选、12 条归档状态、claim-evidence matrix', unlockAt: 4 },
      { title: '可审核长文草稿', detail: '标题、正文、表格和媒体均在重载后验证，不自动发布', unlockAt: 5 },
      { title: '传播素材套装', detail: '6 张 3:4 卡片、PNG ZIP、H.264 MP4 与 qa-report', unlockAt: 5 },
      { title: '个人知识资产', detail: 'Obsidian 事实笔记、决策理由与可重建记忆索引', unlockAt: 6 },
    ],
    meaning: ['一次研究，多种载体', '每步可审计', '失败可恢复', '知识可复用'],
  },
  {
    id: 'research',
    label: '深度研究闭环',
    title: '从模糊问题，到带矛盾与缺口的决策报告',
    summary: '适合产品、市场、竞品和趋势判断：先形成候选，再读取原文，最后让不同模型挑战结论。',
    brief: '示例目标：判断“Agent Skills 是否值得进入团队研发体系”，输出历史演变、当前方案矩阵、风险与采用建议。',
    note: '演示只表达组合方式；来源数量和文件名均为说明性样例。',
    stages: [
      { title: '定义问题与证据门', phase: 'PLAN', skills: ['yichen-web-research'], decision: '明确历史纵轴、当前横轴、地区、受众和不可回答项。', input: '一个模糊战略问题。', operation: '生成研究 brief 与 workstream。', handoff: 'research-brief.json', guard: 'scope 不完整则 fail closed。', effect: '避免先搜一堆资料再临时拼问题。', sample: '示例：3 条纵向工作流｜4 条横向工作流｜2 个不可回答边界' },
      { title: '跨源发现', phase: 'DISCOVER', skills: ['yichen-unified-search'], decision: '按来源类型分配路线，记录每条候选的实际 backend。', input: '查询组、平台与时间范围。', operation: '生成统一 candidate envelope。', handoff: 'candidate-envelope.json', guard: '排名不等于全网热度。', effect: '所有线索进入同一比较结构。', sample: '示例：36 条候选｜8 个一手来源｜6 个实现仓库' },
      { title: '独立挑战', phase: 'CHALLENGE', skills: ['yichen-grok-consult', 'yichen-chatgpt-web-research'], decision: '用两个外部模型寻找反证、遗漏和替代解释。', input: '核心假设与候选摘要。', operation: '只读咨询、X 原生搜索与第二意见。', handoff: 'challenge-notes.md', guard: '模型输出不是一手事实。', effect: '更早暴露单模型偏见与确认偏误。', sample: '示例：4 条反证｜3 个需回到原文核验的主张' },
      { title: '归档一手材料', phase: 'ARCHIVE', skills: ['yichen-content-archive'], decision: '只归档已经确认且真正支撑/反驳主张的材料。', input: '选定 URL 与明确 archive 权限。', operation: '读取、保存并生成 manifest。', handoff: 'evidence/ + archive-manifest.jsonl', guard: 'handoff 不携带新的下载授权。', effect: '研究引用不再依赖易失的搜索摘要。', sample: '示例：14 份一手材料｜每条都有 locator 与 hash' },
      { title: '组装纵横证据', phase: 'SYNTHESIZE', skills: ['yichen-web-research'], decision: '将来源连接到 supports / contradicts claim，并保留冲突和缺口。', input: '原文证据、时间线与挑战记录。', operation: '验证 bundle 结构并生成报告。', handoff: 'decision-report.md + evidence-bundle.json', guard: '脚本验证结构，事实判断仍需 Agent 回读。', effect: '得到能解释“为什么”的决策材料，而非链接清单。', sample: '示例：9 个 claims｜2 个 retained gaps｜3 个可观察 trigger' },
      { title: '沉淀与复用', phase: 'REMEMBER', skills: ['yichen-summary', 'yichen-agent-memory'], decision: '保存结论、证据边界和未来重验触发器。', input: '报告、决策与未决问题。', operation: '写入 Markdown 事实源并更新索引。', handoff: 'decision-memory.md', guard: '派生索引可重建，不反向改写事实。', effect: '下一次研究可以从已知边界继续，而不是重新开场。', sample: '示例：1 个决策记录｜5 个未来复查触发器' },
    ],
    outcomes: [
      { title: '证据化决策报告', detail: '时间线、现状矩阵、支持/反驳关系与保留缺口', unlockAt: 4 },
      { title: '可复查来源包', detail: '一手材料、locator、hash 与真实检索路线', unlockAt: 4 },
      { title: '反方意见记录', detail: '不同模型提出的反证，不与事实证据混写', unlockAt: 2 },
      { title: '下一轮研究起点', detail: '结论、失效条件和未来重验触发器进入事实源', unlockAt: 5 },
    ],
    meaning: ['候选事实分离', '多模型互证', '矛盾不被抹平', '研究可续接'],
  },
  {
    id: 'private',
    label: '私域资产闭环',
    title: '从私人收藏与本地记录，到一份可控的知识周报',
    summary: '适合个人数字资产整理；敏感读取、本地处理、内容归档和外部写入被拆成独立授权阶段。',
    brief: '示例目标：整理本人一周收藏和指定微信会话，生成本地知识周报；确认后再写入企微文档。',
    note: '此场景具有最高隐私风险；模拟不会读取任何真实收藏、聊天或企业数据。',
    stages: [
      { title: '精确授权范围', phase: 'AUTHORIZE', skills: ['yichen-bookmarks-export'], decision: '先确定平台、账号、日期和只导链接的边界。', input: '本人收藏平台 + 本周时间窗。', operation: '只读滚动并提取链接。', handoff: 'bookmarks.txt + export-summary.json', guard: '授权不跨平台、不跨任务。', effect: '私人收藏先变成最小化 URL 清单。', sample: '示例：23 个链接｜0 篇正文读取｜0 个媒体下载' },
      { title: '选择性读取内容', phase: 'ARCHIVE', skills: ['yichen-content-archive'], decision: '用户从 23 个链接中明确选择 8 个允许读取的条目。', input: '8 个确认 URL + read 授权。', operation: '读取正文并生成归档状态。', handoff: 'weekly-reading/ + manifest.jsonl', guard: '收藏导出授权不自动转移给归档。', effect: '只有真正需要的内容进入本地资产。', sample: '示例：8 个输入｜7 个成功｜1 个失败原因保留' },
      { title: '读取本地会话快照', phase: 'LOCAL READ', skills: ['yichen-wechat-local-vault', 'yichen-wechat-windows-reader'], decision: '根据操作系统和用户已准备的数据选择一个本地只读入口，不同时运行两条路线。', input: '指定会话、时间范围或显式静态快照。', operation: '有界查询并导出 Markdown 素材。', handoff: 'conversation-material.md + snapshot manifest', guard: '不自动发现路径，不执行聊天文本中的命令或 URL。', effect: '本地记录变成范围明确、可审阅的周报素材。', sample: '示例：1 个会话｜7 天窗口｜身份匿名化｜原数据库不修改' },
      { title: '本地综合周报', phase: 'SUMMARIZE', skills: ['yichen-summary'], decision: '仅使用授权材料，区分原文事实、个人判断和待办。', input: '7 篇正文 + 会话素材 + 本周决策。', operation: '生成 Obsidian Markdown 周报。', handoff: 'weekly-knowledge-review.md', guard: '隐私筛选和冲突保护必须在写入前完成。', effect: '分散的收藏与讨论成为一个可行动的本地总结。', sample: '示例：5 个主题｜9 条洞见｜4 个待办｜来源逐条可回看' },
      { title: '受控写入团队空间', phase: 'PUBLISH DRAFT', skills: ['yichen-wecom-operations'], decision: '用户确认内容和目标文档后，才调用官方 CLI 创建团队资源。', input: '脱敏周报 + 精确目标 + 当前写入授权。', operation: 'doctor、预检、创建、回读并保存 0600 回执。', handoff: 'WeCom document URL + receipt', guard: '不发消息；删除、取消、覆盖需再次确认。', effect: '私人整理结果经过脱敏和确认后，才成为团队可见知识。', sample: '示例：1 份文档草稿｜errcode=0｜创建与回读状态分别记录' },
      { title: '记忆闭环', phase: 'REMEMBER', skills: ['yichen-agent-memory'], decision: '只将可长期复用的非敏感结论写入共享事实源。', input: '脱敏后的决策和回执。', operation: 'reconcile、claim、closeout 与索引。', handoff: 'memory closeout receipt', guard: '私人原文不因进入周报而自动进入共享记忆。', effect: '团队获得结论，敏感原始材料仍留在个人边界内。', sample: '示例：6 条共享结论｜0 条原始聊天正文进入共享库' },
    ],
    outcomes: [
      { title: '本地阅读包', detail: '仅包含明确选择的正文与逐项归档状态', unlockAt: 1 },
      { title: '个人知识周报', detail: '收藏、会话素材、洞见与待办在本地完成综合', unlockAt: 3 },
      { title: '脱敏团队文档', detail: '人工确认后经官方 CLI 写入，并保留回读回执', unlockAt: 4 },
      { title: '最小共享记忆', detail: '只沉淀长期结论，不传播私人原文', unlockAt: 5 },
    ],
    meaning: ['授权逐段取得', '原始数据本地', '写入前人工确认', '最小化共享'],
  },
];
